title: PHP Sergipe
email: site@phpse.net
description: > # this means to ignore newlines until "baseurl:"
  2012-2016 PHP Sergipe
baseurl: ""
url: "http://phpse.net"
twitter_username: phpse
github_username:  PHPSergipe

# Build settings
markdown: kramdown
